# Generated by Django 4.1.7 on 2023-03-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmapp', '0002_vehicledtls_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledtls',
            name='Vehicle_Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicledtls',
            name='Vehicle_Model',
            field=models.TextField(null=True),
        ),
    ]
